### ISSUE TITLE
2017 A Term

### ISSUE THREAD

**Issue by oyamad** [OyamaZemi/MirandaFackler.notebooks#1]
@OyamaZemi/2017 担当者リストをここに書いてください．

わからないことがあったりしたら新しい issue を立ててください．

**Comment by IoriS** [comment]
Aセメ担当です（敬称略）

8.3.1 - 9.6.1 土屋
8.3.2 - 9.6.2 瀧川
8.4.1 - 9.7.1 小住
8.4.2 - 9.7.2 齊藤
8.4.3 - 9.7.3 高橋
8.4.4 - 9.7.4 津島
8.4.5 - 9.7.5 森
8.4.6 - 9.7.6 優
8.4.7 - 9.7.7 金丸
8.4.8 - 9.7.8 松下
8.5.1 - 9.8.1 金
8.5.2 - 9.8.2 池上
8.5.3 - 9.8.3 佐々木
8.6.1 - 9.9.1 中田

1日に1～1.5個くらいのペースでやる予定だそうです。

**Comment by oyamad** [comment]
発表担当者は，ゼミまでに jupyter notebook を用意して，[README.md](https://github.com/OyamaZemi/MirandaFackler.notebooks/blob/master/README.md) にリンクをはってください (プルリクエストを出す)．

**Comment by oyamad** [comment]
もう教科書の内容は理解できたと思うので，スピードを上げましょう．例えば次回11/20は前回9.7.5とほぼ同じなので1日に2節すすめるはず．

お互い peer review しあって卒論発表ための時間を作りましょう．

**Comment by oyamad** [comment]
@OyamaZemi/2017
Issue を開いている人は，解決したら解決策を書いて close してください．

**Comment by oyamad** [comment]
予定通り終了．
