### ISSUE TITLE
9.7.3

### ISSUE THREAD

**Issue by masashitshit** [OyamaZemi/MirandaFackler.notebooks#16]
土屋君、瀧川さん、小住さん、齊藤さんのを参考に線形補間、チェビシェフ補間、スプライン補間を行いました。
結果、線形補間を行った時のoptimal outputやvalueは教科書と概ね一致しますが(sが2以下になると利益が出ないので生産をストップし、資源の価値も0となる)、チェビシェフ補間などだとsが3の時点でoptimal outputが0となります。（またその後もsが0となるまでvalueが正の値をとる。）funevalを使った当てはめ値がおかしい可能性が高いのですが、理由がよくわかりません。

**Comment by oyamad** [comment]
これどうなりましたか．解決したなら close してください．

ちなみに，教科書とグラフがちょっとずれますが，[ここ](https://github.com/PaulFackler/CompEcon/blob/56e740e9e2e380318e11f79ce8aca92533a964d6/CEdemos/mfdp09.m#L8)にあるように，`p(x)` の `x` の係数を2で割ると教科書と同じグラフになると思います．(教科書は，定式化とグラフが不整合．)

**Comment by masashitshit** [comment]
すいません、解決済みでした。

グラフのずれはそういう理由だったのですね。ありがとうございます！m(＾_＾)m
