### ISSUE TITLE
9.6.1

### ISSUE THREAD

**Issue by NTsuchiya0127** [OyamaZemi/MirandaFackler.notebooks#2]
9.6.1でわからない点がいくつかあるので、質問させてください。
 1.k[t+1]を求めるところで、shockとしてepsilonを使うと思うのですが、そのeはqnwnormで5つのベクトルとして与えられるのですが、これはどのように決定すればよいのでしょうか。
 2.V(k,a)の部分のΣの式の意味がよくわかりません（その後どこで実装されているのかも）
 3.概して7.6.2と同じように作っていっていいのでしょうか？
以上、よろしくお願いします。

**Comment by oyamad** [comment]
1. `epsilon` と `w` は

   ```jl
   using QuantEcon
   sigma = 15
   m = 5
   epsilon, w = qnwnorm(m, 0, sigma^2);
   ```

   とすれば出てくるようです．

2. "Collocation Method" のところに書いてあると思います．
   コーディングは @EikiTakigawa が書いてくれたようにして，value iteration でもやればよいのでは．
   「実装」は Matlab なら[ここ](http://www4.ncsu.edu/%7Epfackler/compecon/toolbox.html)を探せばあると思います (Julia 版はないと思います)．

3. 「概して」の定義によりますが，数学原理は同じですが，数値計算に際しては，連続状態では離散状態と比べて一手間も二手間もかかるということだと思います (それがこの章のテーマ)．

またわからないことがあればここに書いてください．@EikiTakigawa も答えてくれるでしょう (よろしく)．

**Comment by oyamad** [comment]
* オリジナルの MATLAB 版は GitHub にもありました：https://github.com/PaulFackler/CompEcon
* BasicMatrices.jl を使うのがわかりにくければ，離散変数 `a` の取りうる値の数だけ value function を作って，それぞれに `QuantEcon.jl` の `LinInterp` なり，以前の練習課題で作った自前の関数なりを使ってもよいでしょう．
