### ISSUE TITLE
7.6.5 update

### ISSUE THREAD

**Issue by 4kizuki** [OyamaZemi/MirandaFackler.notebooks#25]
http://nbviewer.jupyter.org/github/4kizuki/QuantEcon.notebooks/blob/master/ddp_ex_MF_7_6_5_jl.ipynb

**Comment by oyamad** [comment]
* Iteration の回数が違うのは，Julia 版ではデフォルトは policy iteration ではなく value iteration だからです．明示的に policy iteration を指定しないといけない．
* グラフの値に注意してください．Index ではなく値です (適切に1を引かないといけない)．

**Comment by 4kizuki** [comment]
修正しました

http://nbviewer.jupyter.org/github/4kizuki/QuantEcon.notebooks/blob/master/ddp_ex_MF_7_6_5_jl.ipynb?refresh=true

2017年12月11日 16:11 Daisuke Oyama <notifications@github.com>:

**Comment by oyamad** [comment]
State の方も1ずらすのでは．
