### ISSUE TITLE
9.8.2 income redistribution game Bellman residual

### ISSUE THREAD

**Issue by keiikegami** [OyamaZemi/MirandaFackler.notebooks#26]
Bellman residualが再現できてないです。新しいgrid引きなおして元のモデルとの差をプロットしているのですが、どこかおかしいでしょうか。
https://github.com/keiikegami/IRG/blob/master/share_game.ipynb

**Comment by oyamad** [comment]
* `c` を求めるときに iteration は何回やりましたか．
* 最初に `basis` から作った `S` を使って `resid` を評価するとどのくらいの値になりますか．

**Comment by keiikegami** [comment]
- 新しくあげたnotebookではcを求める際に1万回ループしていますが、cのエラーをみると収束していないようでした。
https://github.com/keiikegami/IRG/blob/master/share_game.ipynb

なのでresidualだけの問題というわけではなさそうです。（なので二つ目のご指摘に関してはやっていません。）

**Comment by oyamad** [comment]
Collocation method は一般には収束は保証されていないと思うので，「それっぽい」初期条件 `initial` を見つけて iteration をやってみてください．

**Comment by keiikegami** [comment]
解決策：元のvmaxでdiscount factorを入れ忘れていた。discount factorを加えると係数は収束したためresidualも適切に求まった。
