### ISSUE TITLE
Residual について

### ISSUE THREAD

**Issue by ghost** [OyamaZemi/MirandaFackler.notebooks#6]
やっぱり residual がよく理解できません 
`BasisMatrices` を使って、補間の形式をなるべく教科書の例に近づけてみたのですが、residual のグラフはうまく再現できませんでした  
  
どなたか residual について分かった方がいたら、教えていただけないでしょうか

**Comment by oyamad** [comment]
[CompEcon-python](https://github.com/randall-romero/CompEcon-python) というのを見つけました．そこで residual をどう計算しているか調べてみてください (Matlab より読みやすいでしょう)．

**Comment by oyamad** [comment]
Growth model しかやってないけど，それっぽいのが出ましたけど：[notebook](http://nbviewer.jupyter.org/github/OyamaZemi/MirandaFackler.notebooks/blob/collocation/collocation/collocation.ipynb)．

**Comment by ghost** [comment]
Collocation method で更新していく補間関数の係数の更新前後の差ということでした
